### ISSUE TITLE
On start up, see different error messages

### ISSUE THREAD

**Issue by dxdc** [techyowl/homebridge-august-smart-locks#18]
On homebridge start up, I see:

`Login was unsuccessful, check your configuration and try again.`

Still, I'm able to control locks just fine.

Enabled logging as follows:
```js
          self.platformLog(error); // added
          self.platformLog("Login was unsuccessful, check your configuration and try again.");
          callback(error);
```

See one of the following POST errors:

```
{ code: 'BadRequest', message: 'token is not a valid lockid' }, statusCode: 400 }
{ code: 'InvalidArgument', message: 'Verification code not found' }, statusCode: 409 }
```

**Comment by dxdc** [comment]
I think the problem may be here - in that, `code` isn't needed/used?

Also, if a new code is required, it will delete existing locks (and of course, any automations).

```js
    var requestingCode = false;
    if (self.code && self.code.length > 2) {
      authorizeRequest.code = self.code;
    } else {
      if (self.codeRequested) {
        callback();
        return;
      }
      requestingCode = true;
    }
```

**Comment by techyowl** [comment]
That is the 2FA code and Im not sure why the error is happening however looking at the August-Connect repo a bit more I don't think the authorize should even be called upon restart of home bridge since that library has its own persistence mechanism that maintains logins that survive the home bridge restarts. I have made a rather "hacky" way to persist data for the platform since I cannot find anywhere in their docs the correct way to do it. Fun fact though is that it could actually be used to detect the 2FA code being added without the need for a second restart since I am now reading the full home bridge config file at runtime for store additional variable(s) and it could be (ab)used unless there is a better method. I couldn't find any better example in the home bridge docs but am open to a different and more standardized method to persist data at the platform level.

**Comment by dxdc** [comment]
@techyowl thanks for looking into this!

As for the persistence, I can help a bit.

1. Add this to your package.json

` "node-persist": "^2.1.0" `

2. Initialize the persistence in the app

```js
    this.cacheDirectory = HomebridgeAPI.user.persistPath();
    this.storage = require('node-persist');
    this.storage.initSync({
        dir: this.cacheDirectory,
        forgiveParseErrors: true,
    });
```

3. Define which variables should be persisted

```js
    this.lastPosition = this.storage.getItemSync('yournamehere') || 0;
```

You can see an example here:

https://github.com/dxdc/homebridge-blinds/

**Comment by techyowl** [comment]
Thats a lot cleaner keeping it isolated. I have a new version ready for when the dependency is updated for august-connect with some new changes.
