### ISSUE TITLE
Remove contact sensor / door sensor

### ISSUE THREAD

**Issue by Kepete** [techyowl/homebridge-august-smart-locks#19]
I'm not using the contact sensor/door sensor of the august lock. I'm only using the lock itself.
Currently there is no option to choose which accessories you want to implement. 

So I have the lock sensor which always shows wrong state, but in addition it seems to mess with the lock states. Locking when door contact is open etc. 

Feature request: make it a variable that can be turned off when no door sensor in use.

**Comment by techyowl** [comment]
I will not use the august door locks without door sense. I cannot test your setup so I cannot reliable develop this feature. Your welcome to create a PR to implement this yourself otherwise I will close this out as won't implement. Door sense improves the august lock experience a lot I'm kind of curious why you don't use them?
